apiVersion: v1
kind: Service
metadata:
  name: fastapi-gitops
  namespace: staging
  labels:
    app: fastapi-gitops
    environment: staging
spec:
  type: LoadBalancer
  selector:
    app: fastapi-gitops
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
